---

- name: Install report tools
  ansible.builtin.package:
    name: "{{ sysmon_report_pkgs }}"
    state: present

- name: Ensure /usr/local/scripts exists
  ansible.builtin.file:
    dest: /usr/local/scripts
    state: directory
    mode: '0755'

- name: Ensure /opt/sysmon has traversal permission
  ansible.builtin.file:
    dest: /opt/sysmon
    mode: '0711'

- name: Ensure sysmonLogView can be used by non-root users
  ansible.builtin.file:
    dest: /opt/sysmon/sysmonLogView
    mode: '0755'
  when:
    - not is_container|bool

- name: Ensure reporting script exists
  ansible.builtin.template:
    src: "{{ sysmon_reporting_template }}.j2"
    dest: "/usr/local/scripts/{{ sysmon_reporting_template | basename }}"
    mode: '0755'

- name: Creates a daily scheduled task for reporting
  ansible.builtin.cron:
    name: sysmon_reporting
    minute: "40"
    hour: "23"
    user: "syslog"
    job: "/usr/local/scripts/{{ sysmon_reporting_template | basename }}"
    cron_file: ansible_sysmon_reporting
