---

- name: Ensure build dependencies are present
  ansible.builtin.package:
    name: "{{ sysmon_build_pkgs }}"
    state: present

- name: Import mono-t4
  ansible.builtin.import_tasks: mono-t4.yml

- name: Ensure google test build directory exists
  ansible.builtin.file:
    dest: "/usr/src/googletest/build"
    state: directory
    mode: '0700'
    owner: nobody

- name: Build googletest dependency
  ansible.builtin.command: "{{ item.c }}"
  become: "{{ item.b }}"
  become_user: "{{ item.bu }}"
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: "cmake ..", chdir: "/usr/src/googletest/build", t: "/usr/src/googletest/build/Makefile", b: yes, bu: nobody }
    - { c: make, chdir: "/usr/src/googletest/build", t: "{{ sysmon_libgtest_path }}", b: yes, bu: nobody }
    - { c: make install, chdir: "/usr/src/googletest/build", t: "/usr/local/lib/libgtest.a", b: yes, bu: root }

- name: Git clone SysmonForLinux repo
  ansible.builtin.git:
    repo: https://github.com/Sysinternals/SysmonForLinux.git
    dest: "{{ sysmon_build_dir }}"
    version: "{{ sysmon_git_version }}"

- name: Ensure build directory exists
  ansible.builtin.file:
    dest: "{{ sysmon_build_dir }}/build"
    state: directory
    mode: '0700'
    owner: nobody

- name: Build sysmon packages - cmake
  ansible.builtin.command: "{{ item.c }}"
  # become: yes
  # become_user: nobody
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: "cmake ..", chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/Makefile" }

- name: Workaround | explicit call to mono
  ansible.builtin.replace:  # noqa no-tabs
    dest: "{{ sysmon_build_dir }}/build/{{ item }}"
    regexp: "^\t/usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe"
    replace: "\tmono /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe"
  loop:
    - CMakeFiles/sysmonLogView.dir/build.make
    - CMakeFiles/sysmon.dir/build.make
    - CMakeFiles/sysmonUnitTests.dir/build.make

- name: Build sysmon packages
  ansible.builtin.command: "{{ item.c }}"
  # become: yes
  # become_user: nobody
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: whoami, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/sysmon" }
    - { c: env, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/sysmon" }
    - { c: make, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/sysmon" }
    - { c: make packages, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/deb/sysmonforlinux_{{ sysmon_build_version }}_amd64.deb" }
  environment:
    VERSION: "{{ sysmon_build_version }}"
