---

- name: Ensure build dependencies are present
  package:
    name: "{{ sysmon_build_pkgs }}"
    state: present

- name: Ensure google test build directory exists
  file:
    dest: "/usr/src/googletest/build"
    state: directory
    mode: '0700'
    owner: nobody

- name: Build googletest dependency
  command: "{{ item.c }}"
  become: "{{ item.b }}"
  become_user: "{{ item.bu }}"
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: "cmake ..", chdir: "/usr/src/googletest/build", t: "/usr/src/googletest/build/Makefile", b: yes, bu: nobody }
    - { c: make, chdir: "/usr/src/googletest/build", t: "{{ sysmon_libgtest_path }}", b: yes, bu: nobody }
    - { c: make install, chdir: "/usr/src/googletest/build", t: "/usr/local/lib/libgtest.a", b: yes, bu: root }

- name: Git clone SysmonForLinux repo
  git:
    repo: https://github.com/Sysinternals/SysmonForLinux.git
    dest: "{{ sysmon_build_dir }}"
    version: "{{ sysmon_git_version }}"

- name: Ensure build directory exists
  file:
    dest: "{{ sysmon_build_dir }}/build"
    state: directory
    mode: '0700'
    owner: nobody

- name: Build sysmon packages - cmake
  command: "{{ item.c }}"
  become: yes
  become_user: nobody
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: "cmake ..", chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/Makefile" }

- name: Workaround | explicit call to mono
  replace:  # noqa no-tabs
    dest: "{{ sysmon_build_dir }}/build/{{ item }}"
    regexp: "^\t/usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe"
    replace: "\tmono /usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe"
  loop:
    - CMakeFiles/sysmonLogView.dir/build.make
    - CMakeFiles/sysmon.dir/build.make
    - CMakeFiles/sysmonUnitTests.dir/build.make

- name: Build sysmon packages
  command: "{{ item.c }}"
  become: yes
  become_user: nobody
  args:
    chdir: "{{ item.chdir }}"
    creates: "{{ item.t }}"
  with_items:
    - { c: make, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/sysmon" }
    - { c: make packages, chdir: "{{ sysmon_build_dir }}/build", t: "{{ sysmon_build_dir }}/build/deb/sysmonforlinux_{{ sysmon_build_version }}-1_amd64.deb" }
