---

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when:
    - not is_container|bool

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  when:
    - not is_container|bool

- name: Restart sysmon
  ansible.builtin.service:
    name: sysmon
    state: restarted
  when:
    - not is_container|bool

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
