---

- name: Verify
  hosts: sysmon
  tasks:

    - name: Get /opt/sysmon/config.xml stats
      ansible.builtin.stat:
        path: /opt/sysmon/config.xml
      register: sysmonp
    - name: Validate /opt/sysmon/config.xml exists
      ansible.builtin.assert:
        that: sysmonp.stat.exists and sysmonp.stat.size != 0

    - name: Print sysmon configuration schema definition
      ansible.builtin.command: sysmon -s
      register: grub
      changed_when: false
