---
name: default-bare

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # run weekly, every monday 03:00
    - cron: '0 3 * * 1'

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    runs-on: ${{ matrix.distribution }}-${{ matrix.version }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - distribution: ubuntu
            version: '22.04'
            experimental: true
          - distribution: ubuntu
            version: '20.04'
            experimental: true
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks

    steps:
      - uses: actions/checkout@v3
        with:
          path: juju4.sysmon
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible-lint flake8 yamllint
          which ansible
          pip3 install ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ls -l /opt/hostedtoolcache/Python/3.9.1/x64/bin || true
          echo "/opt/hostedtoolcache/Python/3.9.1/x64/bin" >> $GITHUB_PATH
          ansible --version
          cd $GITHUB_WORKSPACE/juju4.sysmon
          [ -f get-dependencies.sh ] && sh -x get-dependencies.sh
          { echo '[defaults]'; echo 'callbacks_enabled = profile_tasks, timer'; echo 'roles_path = ../'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Environment
        run: |
          pwd
          env
          find -ls
      - name: Before script - systemctl
        run: |
          systemd-analyze security || true
          systemctl status --all --no-pager || true
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/juju4.sysmon && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: idempotency run
        run: |
          cd $GITHUB_WORKSPACE/juju4.sysmon && ansible-playbook -i localhost, --connection=local --become -vvv molecule/default/converge.yml | tee /tmp/idempotency.log | grep -q 'changed=0.*failed=0'  && (echo 'Idempotence test: pass' && exit 0)  || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)
      - name: On failure
        run: |
          systemctl -l --no-pager status
        if: env.WORKFLOW_CONCLUSION == 'failure'  # notify only if failure
      - name: After script - systemctl
        run: |
          systemd-analyze security || true
          systemctl --failed || true
          systemctl status sysmon || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - journalctl
        run: |
          journalctl -xe -u sysmon
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - files
        run: |
          sudo ls -la /opt/sysmon/
          sudo getfacl /opt/sysmon/sysmon
          sudo getfacl /opt/sysmon/sysmonLogView
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - sysmon
        run: |
          set -x
          sysmon -s || true
          sudo cat /opt/sysmon/config.xml || true
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - resulting systemd config
        run: |
          set -x
          cat /etc/systemd/system/sysmon.service || true
          find /etc/systemd/system/sysmon.service.d/ -type f -exec cat {} \;
        if: ${{ always() }}
        continue-on-error: true
      - name: After script - reporting
        run: |
          set -x
          TEE=false sh -x /usr/local/scripts/sysmon_report.sh
        if: ${{ always() }}
        continue-on-error: true
